server:
  port: 8443  # HTTPS Port
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456  # This is your SSL password
    key-store-type: PKCS12
    key-alias: mysslcert
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/journal_entries
    username: postgres
    password: 3217
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Change to 'create' if auto-creating tables

  data:
    redis:
      repositories:
        enabled: false  # Disable Redis repositories if using Redis only as a cache
      host: journal-app  # Redis is in Docker with name 'journal-app'
      port: 6379
      database: 0

  kafka:
    bootstrap-servers: localhost:9092  # Kafka is running inside Docker
    security.protocol: PLAINTEXT  # No SSL for local Kafka setup
    consumer:
      group-id: journal-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.springframework.security: DEBUG  # Change to INFO or WARN in production
    org.apache.kafka: INFO
